### ISSUE TITLE
Please give Milan access to the Amazon S3 geonarrative bucket

### ISSUE THREAD

**Issue by jamvelk** [USGS-WiM/Geonarratives#5]
Please give @milanliu access to the Amazon S3 wim.usgs.gov/geonarrative bucket, so she can assist with hosting geonarrative templates @aaronstephenson (sorry Aaron I tried to assign this task to you but it's not giving me the option, hoping you see this)

**Comment by aaronstephenson** [comment]
New IAM user created for Milan, and the S3_wim.usgs.gov policy added to her account, which will give her access to the geonarratives folder within that bucket. Credentials emailed to Milan.

**Comment by jamvelk** [comment]
@aaronstephenson @milanliu is having trouble logging in at the wim.usgs.gov bucket: 
![image](https://user-images.githubusercontent.com/15385142/134981548-6d2c3981-50f1-4b9d-8035-32efb495dc12.png)

**Comment by aaronstephenson** [comment]
OK give it another try. Looks like the S3_wim.usgs.gov policy attachment didn't "take" last time, or maybe I didn't click the button correctly.

**Comment by jamvelk** [comment]
thanks @aaronstephenson , it worked!
