### ISSUE TITLE
Follow up on Luke Sturtevant's question on fitting Dashboard in iframe

### ISSUE THREAD

**Issue by jamvelk** [USGS-WiM/Geonarratives#7]
@mitchas Mitch would you please respond to the email chain about the Noreaster2018 Dashboard, reply to Luke Sturtevant.

Copied you on the email Chain on 10/1.  Question is: is there a way to customize the extent of the Dashboard within the iframe? 

Original email from Luke on 10/1/2021

Thanks for the information.  I've created the HTML file and attached it to this email.  The dashboard has not been made public yet, so it requires AGOL sign-in for USGS users.  I'm hoping that we can customize the extent and size of the dashboard within the iframe because the dashboard is squashed inside the iframe and appears to remove some of the filtering options and charts. The URL I would like to use for this dashboard is: wim.usgs.gov/geonarrative/newenglandnoreaster2018dashboard

![image](https://user-images.githubusercontent.com/15385142/137350123-9b6a2956-7fbc-4a40-8372-af31bd56a1a3.png)

**Comment by milanliu** [comment]
Cooperator followed up that this was an issue with his own browser sizing and has now been resolved!
